"""Initial schema setup from sql

Revision ID: f944d5e1504c
Revises: 
Create Date: 2026-03-03 21:58:07.307416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f944d5e1504c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('penalty_log')
    op.drop_table('notifications')
    op.drop_table('qr_log')
    op.drop_table('user_badges')
    op.drop_table('credits')
    op.drop_table('fraud_flags')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('roll_number'))

    op.drop_table('users')
    op.drop_table('resources')
    op.drop_table('badges')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('transaction_id'))

    op.drop_table('transactions')
    op.drop_table('ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rater_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ratee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('communication_rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeliness_rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condition_rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_rating', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('(`communication_rating` between 1 and 5)', name=op.f('ratings_chk_1')),
    sa.CheckConstraint('(`condition_rating` between 1 and 5)', name=op.f('ratings_chk_3')),
    sa.CheckConstraint('(`timeliness_rating` between 1 and 5)', name=op.f('ratings_chk_2')),
    sa.ForeignKeyConstraint(['ratee_id'], ['users.id'], name=op.f('ratings_ibfk_3')),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name=op.f('ratings_ibfk_2')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('ratings_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('request_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('borrower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits_transferred', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('security_deposit', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', mysql.ENUM('Initiated', 'ItemCollected', 'Active', 'Returned', 'Penalized', 'Disputed'), server_default=sa.text("'Initiated'"), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('collected_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('returned_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('qr_hash', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('return_qr_hash', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('penalty_applied', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], name=op.f('transactions_ibfk_2')),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], name=op.f('transactions_ibfk_3')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('transactions_ibfk_1')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('transactions_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('transaction_id'), ['transaction_id'], unique=True)

    op.create_table('badges',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('criteria_type', mysql.ENUM('transactions', 'credits_earned', 'trust_score', 'lending_streak'), server_default=sa.text("'transactions'"), nullable=True),
    sa.Column('criteria_value', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resources',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('category', mysql.ENUM('Electronics', 'Books', 'Sports', 'Tools', 'Clothing', 'Academic', 'Skill', 'Other'), server_default=sa.text("'Other'"), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('available_from', sa.DATE(), nullable=True),
    sa.Column('available_until', sa.DATE(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('security_deposit', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('credits_per_day', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('status', mysql.ENUM('Available', 'Borrowed', 'Unavailable'), server_default=sa.text("'Available'"), nullable=True),
    sa.Column('resource_type', mysql.ENUM('Resource', 'Skill', 'Knowledge'), server_default=sa.text("'Resource'"), nullable=True),
    sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('resources_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('roll_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('Student', 'Faculty', 'Admin'), server_default=sa.text("'Student'"), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_frozen', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('trust_score', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'5.00'"), nullable=True),
    sa.Column('verification_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('violation_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('roll_number'), ['roll_number'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('fraud_flags',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flag_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('reviewed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fraud_flags_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('credits',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'100.00'"), nullable=True),
    sa.Column('locked_credits', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('total_earned', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('total_spent', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credits_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_badges',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badge_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('earned_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name=op.f('user_badges_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_badges_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('qr_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('qr_type', mysql.ENUM('Collection', 'Return'), server_default=sa.text("'Collection'"), nullable=True),
    sa.Column('qr_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('used_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.ENUM('info', 'success', 'warning', 'danger'), server_default=sa.text("'info'"), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('penalty_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('applied_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('penalty_log_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('penalty_log_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('borrower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('borrow_days', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('total_credits', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', mysql.ENUM('Pending', 'Approved', 'Rejected', 'Active', 'Returned', 'Cancelled'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], name=op.f('requests_ibfk_2')),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], name=op.f('requests_ibfk_3')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('requests_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
